name: Deploy Admin Page

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:
  deploy:
    name: Deploy to server
    runs-on: ['self-hosted', 'ARM64']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install
      - name: Generate .env file
        run: |
          echo "VITE_APP_API_URL=$VITE_APP_API_URL">>.env
        env:
          VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
      - name: Build
        run: yarn build
      - name: Copy built files to server
        run: |
          cp -r dist/* /home/ubuntu/hyuabot-admin-frontend/